/**
 * Every localStorage key the app reads or writes, in one place.
 *
 * These keys are inherited verbatim from the original standalone HTML apps
 * (`index.html`, `Unseen New.html`, `Modules Practice.html`). They must not be
 * renamed: the sync-link feature ships raw key/value pairs between devices, so
 * a link generated by an old build has to keep importing cleanly, and returning
 * users must keep their progress.
 */
export const StorageKeys = {
  /** `'1'` / `'0'`. Also drives the Mantine colour scheme, see colorSchemeManager. */
  darkMode: "dark_mode_enabled",
  /** `'1'` / `'0'`. Written by the Unseen page in the originals. */
  dyslexiaFont: "dyslexia_font_enabled",
  /** `'1'` / `'0'`. The Modules page's separate copy of the same preference. */
  dyslexiaFontModules: "dyslexia_font_enabled_modules",
  /** Speech rate as a decimal string. New: the originals read it live off the
   *  slider and never persisted it. `english_` prefixed so it also syncs. */
  speechRate: "english_speech_rate",
  /** UI language, `'he'` or `'en'`. New in the React app. */
  locale: "english_locale",
  /** `voiceURI` of the chosen system speech voice. New in the React app. */
  systemVoice: "english_system_voice",

  /** `Record<exerciseId, Exercise>` */
  exerciseLibrary: "english_exercise_library",
  /** Plain exercise id string. */
  currentExerciseId: "english_current_exercise_id",
  /** Legacy mirror of the active exercise object, kept for back-compat. */
  currentExerciseData: "current_english_exercise_data",
  /** `Record<exerciseId, string[]>`. New: the originals highlighted words in
   *  the DOM only, so the marks were lost on every re-render. */
  markedWords: "english_marked_words",
  /** `Record<questionId, {selected, correct}>` for the active exercise. New:
   *  in-progress quiz answers used to be wiped on every reload. */
  quizAnswers: "english_quiz_answers",
  /** Flashcard deck position for the active exercise. New: the originals
   *  always reopened on the first card. */
  flashcardIndex: "english_flashcard_index",

  /** `Module[]` */
  allModules: "english_reading_all_modules_v4",
  /** `Record<word, 'known' | 'unknown'>` */
  modulesProgress: "english_reading_practice_progress_v3",
  /** Ids of built-in modules the user deleted, so they are not re-seeded. */
  deletedBuiltInModules: "english_reading_deleted_builtins_v1",
  /** Module deck position for the active module. New: the originals always
   *  reopened on the first card. */
  moduleCardIndex: "english_module_card_index",
  /** Plain module id string. New: the originals always reopened on a
   *  hardcoded module regardless of what the user was last practising. */
  currentModuleId: "english_current_module_id",
} as const

/** `flashcards_status_<exerciseId>` -> `Record<word, boolean>` (true = known). */
export const flashcardStatusKey = (exerciseId: string) =>
  `flashcards_status_${exerciseId || "default"}`

/** Matches any key the sync feature should carry between devices. */
export const isSyncableKey = (key: string) =>
  key.startsWith("flashcards_status_") ||
  key.startsWith("english_") ||
  key.includes("dyslexia") ||
  key.includes("dark_mode")
