/**
 * Every localStorage key the app reads or writes, in one place.
 *
 * These keys are inherited verbatim from the original standalone HTML apps
 * (`index.html`, `Unseen New.html`, `Modules Practice.html`). They must not be
 * renamed: both the `?s=` sync-link feature and the Google Drive sync
 * (`docs/google-account-sync.md`) ship the syncable subset of these key/value
 * pairs verbatim, as the link's payload or as the Drive file's JSON, so a link
 * or Drive snapshot generated by an old build has to keep importing cleanly,
 * and returning users must keep their progress.
 */
export const StorageKeys = {
  /** `'1'` / `'0'`. Also drives the Mantine colour scheme, see colorSchemeManager. */
  darkMode: "dark_mode_enabled",
  /** `'1'` / `'0'`. Written by the Unseen page in the originals. */
  dyslexiaFont: "dyslexia_font_enabled",
  /** Speech rate as a decimal string, for English content. New: the
   *  originals read it live off the slider and never persisted it. */
  speechRate: "english_speech_rate",
  /** Speech rate as a decimal string, for Hebrew content (module rules).
   *  Separate from `speechRate` so the two languages can run at different
   *  speeds. */
  speechRateHe: "hebrew_speech_rate",
  /** UI language, `'he'` or `'en'`. New in the React app. */
  locale: "english_locale",
  /** `voiceURI` of the chosen system speech voice for English content. New in the React app. */
  systemVoice: "english_system_voice",
  /** `voiceURI` of the chosen system speech voice for Hebrew content (module
   *  rules, UI-adjacent Hebrew text). New in the React app. */
  systemVoiceHe: "hebrew_system_voice",
  /** GIS access token. Device-local — must never appear in `?s=` or Drive. */
  googleAccessToken: "google_access_token",
  /** Hash of the payload as of the last successful Drive sync (push or pulled
   *  apply). Device-local; drives the dirty check in `driveSync.ts`. */
  googleLastSyncedHash: "google_last_synced_hash",

  /** `Record<exerciseId, Exercise>` */
  exerciseLibrary: "english_exercise_library",
  currentExerciseId: "english_current_exercise_id",
  /** Legacy mirror of the active exercise object, kept for back-compat. */
  currentExerciseData: "current_english_exercise_data",
  /** `Record<exerciseId, string[]>`. New: the originals highlighted words in
   *  the DOM only, so the marks were lost on every re-render. */
  markedWords: "english_marked_words",
  /** `Record<questionId, {selected, correct}>` for the active exercise. */
  quizAnswers: "english_quiz_answers",
  /** Flashcard deck position for the active exercise. */
  flashcardIndex: "english_flashcard_index",

  /** `Module[]` */
  allModules: "english_reading_all_modules_v4",
  /** `Record<word, 'known' | 'unknown'>` */
  modulesProgress: "english_reading_practice_progress_v3",
  /** Ids of built-in modules the user deleted, so they are not re-seeded. */
  deletedBuiltInModules: "english_reading_deleted_builtins_v1",
  /** Module deck position for the active module. */
  moduleCardIndex: "english_module_card_index",
  currentModuleId: "english_current_module_id",
} as const

/** `flashcards_status_<exerciseId>` -> `Record<word, boolean>` (true = known). */
export const flashcardStatusKey = (exerciseId: string) =>
  `flashcards_status_${exerciseId || "default"}`

/**
 * Persisted, but deliberately never shared: a `voiceURI` names a voice installed
 * on one machine, and the Google access token must not ride in `?s=` links or
 * the Drive file.
 */
const DEVICE_LOCAL_KEYS = new Set<string>([
  StorageKeys.systemVoice,
  StorageKeys.systemVoiceHe,
  StorageKeys.googleAccessToken,
  StorageKeys.googleLastSyncedHash,
])

/** Matches any key the sync feature should carry between devices. */
export const isSyncableKey = (key: string) =>
  !DEVICE_LOCAL_KEYS.has(key) &&
  (key.startsWith("flashcards_status_") ||
    key.startsWith("english_") ||
    key.startsWith("hebrew_") ||
    key.includes("dyslexia") ||
    key.includes("dark_mode"))
