/**
 * Seed content extracted verbatim from `Unseen New.html`.
 *
 * Generated by `scripts/extract-legacy-data.cjs` -- do not edit by hand.
 */
import type { UnseenExercise } from "@/types/exercise"

export const defaultUnseenExercise: UnseenExercise = {
  title: "📖 תרגול קריאה באנגלית (Reading Practice)",
  subtitle: "נושא: אפיית סופלה (Baking a Soufflé) • רמה בינונית-מתקדמת",
  exerciseId: "souffle_v1",
  paragraphs: [
    "Maya decided to bake a chocolate soufflé, which is known to be a delicate and challenging dessert.",
    "First, she carefully separated the egg whites from the yolks to ensure the batter would rise properly.",
    "While whisking the egg whites, she added a pinch of salt to help create stiff peaks.",
    "She knew that opening the oven door too early would cause the soufflé to collapse due to the sudden temperature change.",
    "Although the process required intense patience and precision, the final result was light, fluffy, and delicious.",
    "Her guests were thoroughly impressed by her culinary skill!",
  ],
  questions: [
    {
      id: "q1",
      title: "1. מדוע מיה הפרידה בזהירות את חלבוני הביצים (הלבנים) מהחלמונים?",
      options: [
        {
          text: "a) To make the dessert bake much faster",
          isCorrect: false,
        },
        {
          text: "b) To help the batter rise properly in the oven",
          isCorrect: true,
        },
        {
          text: "c) Because she needed only yolks for the recipe",
          isCorrect: false,
        },
        {
          text: "d) To change the color of the chocolate",
          isCorrect: false,
        },
      ],
    },
    {
      id: "q2",
      title: "2. מה הסיכון בפתיחת דלת התנור מוקדם מדי בזמן האפייה?",
      options: [
        {
          text: "a) The chocolate will become too sweet",
          isCorrect: false,
        },
        {
          text: "b) The egg whites will lose their saltiness",
          isCorrect: false,
        },
        {
          text: "c) The soufflé might collapse from the sudden temperature drop",
          isCorrect: true,
        },
        {
          text: "d) The oven will stop working immediately",
          isCorrect: false,
        },
      ],
    },
    {
      id: "q3",
      title:
        "3. מה מיה הוסיפה בזמן הקצפת החלבונים כדי להגיע לקצף יציב (stiff peaks)?",
      options: [
        {
          text: "a) Extra chocolate syrup",
          isCorrect: false,
        },
        {
          text: "b) A pinch of salt",
          isCorrect: true,
        },
        {
          text: "c) Warm milk",
          isCorrect: false,
        },
        {
          text: "d) Fresh berries",
          isCorrect: false,
        },
      ],
    },
    {
      id: "q4",
      title: "4. מה ניתן להסיק (to infer) מהטקסט לגבי הכנת סופלה?",
      options: [
        {
          text: "a) It is a simple dish that requires no attention to detail",
          isCorrect: false,
        },
        {
          text: "b) It demands patience, precision, and careful handling",
          isCorrect: true,
        },
        {
          text: "c) Most guests usually dislike its fluffy texture",
          isCorrect: false,
        },
        {
          text: "d) It requires keeping the oven door open while baking",
          isCorrect: false,
        },
      ],
    },
  ],
  flashcards: [
    {
      en: "Delicate",
      he: "עדין / רגיש",
      trans: "דֶלִיקֶט",
    },
    {
      en: "Challenging",
      he: "מאתגר",
      trans: "צֶ'לֶנְגִ'ינְג",
    },
    {
      en: "Separated",
      he: "הפרידה / הופרד",
      trans: "סֶפָרֵייטֶד",
    },
    {
      en: "Batter",
      he: "בלילה",
      trans: "בֶּטֶר",
    },
    {
      en: "Whisking",
      he: "להקציף / הקצפה",
      trans: "וִוויסְקִנְג",
    },
    {
      en: "Collapse",
      he: "לקרוס / קריסה",
      trans: "קוֹלָאפְּס",
    },
    {
      en: "Precision",
      he: "דיוק",
      trans: "פְּרֶסִיזָ'ן",
    },
    {
      en: "Fluffy",
      he: "אוורירי / רך",
      trans: "פְלָאפִי",
    },
    {
      en: "Culinary",
      he: "קולינרי / של בישול",
      trans: "כָּאלִינָרִי",
    },
  ],
}
