/**
 * Seed content extracted verbatim from `Modules Practice.html`.
 *
 * Generated by `scripts/extract-legacy-data.cjs` -- do not edit by hand.
 */
import type { PracticeModule } from "@/types/module"

/** The five built-in phonics modules. */
export const defaultModules: PracticeModule[] = [
  {
    id: "mod1",
    tabName: "מודול 1 (A)",
    title: "מודול 1: תנועת A קצרה (Short A)",
    rule: '\n                    <div class="rule-section"><b>הסבר וחוקיות:</b> באנגלית, כשהאות <b>A</b> מופיעה באמצע מילה קצרה במבנה של עיצור-תנועה-עיצור (CVC), היא מקבלת צליל "אֶה" פתוח (כמו משהו בין פתח לסגול).</div>\n                    <div class="rule-section"><b>סימון הניקוד:</b> עבור הלמידה שלנו, נסמן את הצליל הזה תמיד עם <b>פתַח ( ַ )</b>.</div>\n                    <div class="rule-examples">\n                        <b>דוגמאות להסבר בלבד (לא מופיעות בתרגול):</b><br>\n                        • <b>CAT</b> (כַּט) - חתול<br>\n                        • <b>BAG</b> (בַּג) - תיק<br>\n                        • <b>MAP</b> (מַפ) - מפה\n                    </div>\n                ',
    cards: [
      {
        en: "HAT",
        he: "הַט",
        meaning: "כובע",
      },
      {
        en: "MAN",
        he: "מַן",
        meaning: "איש",
      },
      {
        en: "SAD",
        he: "סַד",
        meaning: "עצוב",
      },
      {
        en: "BAT",
        he: "בַּט",
        meaning: "עטלף / מחבט",
      },
      {
        en: "FAN",
        he: "פַן",
        meaning: "מאוורר",
      },
      {
        en: "JAM",
        he: "גַ'ם",
        meaning: "ריבה",
      },
      {
        en: "PAN",
        he: "פַן",
        meaning: "מחבת",
      },
      {
        en: "RAT",
        he: "רַט",
        meaning: "חולדה",
      },
      {
        en: "VAN",
        he: "וַן",
        meaning: "מסחרית",
      },
      {
        en: "CAB",
        he: "כַּב",
        meaning: "מונית",
      },
      {
        en: "CAP",
        he: "כַּפ",
        meaning: "כובע מצחיה",
      },
      {
        en: "DAD",
        he: "דַד",
        meaning: "אבא",
      },
      {
        en: "LAP",
        he: "לַפ",
        meaning: "חיק / סיבוב",
      },
      {
        en: "MAT",
        he: "מַט",
        meaning: "שטיחון",
      },
      {
        en: "NAP",
        he: "נַפ",
        meaning: "תנומה",
      },
      {
        en: "TAP",
        he: "טַפ",
        meaning: "ברז",
      },
      {
        en: "BAD",
        he: "בַּד",
        meaning: "רע",
      },
      {
        en: "MAD",
        he: "מַד",
        meaning: "כועס",
      },
    ],
  },
  {
    id: "mod2",
    tabName: "מודול 2 (O)",
    title: "מודול 2: תנועת O קצרה (Short O)",
    rule: '\n                    <div class="rule-section"><b>הסבר וחוקיות:</b> כשהאות <b>O</b> מופיעה באמצע מילה קצרה, היא מקבלת צליל "אוֹ" קצר ופתוח (כמו במילה אור).</div>\n                    <div class="rule-section"><b>סימון הניקוד:</b> נסמן את הצליל הזה תמיד עם <b>חֹלם ( ֹ )</b> כדי ליצור הפרדה ברורה מהאות A (פתח).</div>\n                    <div class="rule-examples">\n                        <b>דוגמאות להסבר בלבד (לא מופיעות בתרגול):</b><br>\n                        • <b>DOG</b> (דֹּג) - כלב<br>\n                        • <b>HOT</b> (הֹט) - חם<br>\n                        • <b>BOX</b> (בֹּכּס) - קופסה\n                    </div>\n                ',
    cards: [
      {
        en: "FOX",
        he: "פֹכּס",
        meaning: "שועל",
      },
      {
        en: "TOP",
        he: "טֹפ",
        meaning: "למעלה / סביבון",
      },
      {
        en: "MOP",
        he: "מֹפ",
        meaning: "מגב",
      },
      {
        en: "POT",
        he: "פֹט",
        meaning: "סיר",
      },
      {
        en: "NOT",
        he: "נֹט",
        meaning: "לא",
      },
      {
        en: "DOT",
        he: "דֹּט",
        meaning: "נקודה",
      },
      {
        en: "JOB",
        he: "גֹ'ב",
        meaning: "עבודה",
      },
      {
        en: "LOG",
        he: "לֹג",
        meaning: "בול עץ",
      },
      {
        en: "POP",
        he: "פֹפ",
        meaning: "פופ / פקק",
      },
      {
        en: "ROB",
        he: "רֹב",
        meaning: "לשדוד",
      },
      {
        en: "SOB",
        he: "סֹב",
        meaning: "לייבב",
      },
      {
        en: "HOP",
        he: "הֹפ",
        meaning: "לקפוץ",
      },
      {
        en: "COP",
        he: "כֹּפ",
        meaning: "שוטר",
      },
      {
        en: "COD",
        he: "כֹּד",
        meaning: "דג קוד",
      },
      {
        en: "FOG",
        he: "פֹג",
        meaning: "ערפל",
      },
      {
        en: "GOT",
        he: "גֹט",
        meaning: "קיבל / השיג",
      },
      {
        en: "ROD",
        he: "רֹד",
        meaning: "חכה / מוט",
      },
      {
        en: "ROT",
        he: "רֹט",
        meaning: "להירקב",
      },
    ],
  },
  {
    id: "rev1_2",
    tabName: "מסכם 1+2",
    title: "תרגול מסכם: מודולים 1 + 2 (A, O)",
    rule: '\n                    <div class="rule-section"><b>מטרת התרגול:</b> חיזוק הזיכרון לטווח ארוך והבחנה (Discrimination) בין תנועת <b>A (פתח)</b> לתנועת <b>O (חולם)</b>.</div>\n                    <div class="rule-section"><b>טיפ ללמידה:</b> לפני הקריאה, התמקדו באות התנועתית באמצע המילה – אם זו <b>A</b> מותחים את הפה (פתח), אם זו <b>O</b> מעגלים את השפתיים (חולם).</div>\n                ',
    cards: [
      {
        en: "HAT",
        he: "הַט",
        meaning: "כובע (פתח)",
      },
      {
        en: "FOX",
        he: "פֹכּס",
        meaning: "שועל (חולם)",
      },
      {
        en: "MAN",
        he: "מַן",
        meaning: "איש (פתח)",
      },
      {
        en: "POT",
        he: "פֹט",
        meaning: "סיר (חולם)",
      },
      {
        en: "SAD",
        he: "סַד",
        meaning: "עצוב (פתח)",
      },
      {
        en: "DOT",
        he: "דֹּט",
        meaning: "נקודה (חולם)",
      },
      {
        en: "BAT",
        he: "בַּט",
        meaning: "מחבט (פתח)",
      },
      {
        en: "JOB",
        he: "גֹ'ב",
        meaning: "עבודה (חולם)",
      },
      {
        en: "FAN",
        he: "פַן",
        meaning: "מאוורר (פתח)",
      },
      {
        en: "LOG",
        he: "לֹג",
        meaning: "בול עץ (חולם)",
      },
      {
        en: "JAM",
        he: "גַ'ם",
        meaning: "ריבה (פתח)",
      },
      {
        en: "POP",
        he: "פֹפ",
        meaning: "פופ (חולם)",
      },
      {
        en: "PAN",
        he: "פַן",
        meaning: "מחבת (פתח)",
      },
      {
        en: "HOP",
        he: "הֹפ",
        meaning: "לקפוץ (חולם)",
      },
      {
        en: "RAT",
        he: "רַט",
        meaning: "חולדה (פתח)",
      },
      {
        en: "COP",
        he: "כֹּפ",
        meaning: "שוטר (חולם)",
      },
      {
        en: "DAD",
        he: "דַד",
        meaning: "אבא (פתח)",
      },
      {
        en: "FOG",
        he: "פֹג",
        meaning: "ערפל (חולם)",
      },
    ],
  },
  {
    id: "mod3",
    tabName: "מודול 3 (I)",
    title: "מודול 3: תנועת I (חיריק) ומילים של 4 אותיות",
    rule: '\n                    <div class="rule-section"><b>הסבר וחוקיות:</b> האות <b>I</b> במילים קצרות מקבלת צליל "אִי" קצר וחד. נסמן אותה תמיד ב<b>חִירִיק ( ִ )</b>.</div>\n                    <div class="rule-section"><b>עליית מדרגה:</b> מתחילים לשלב מילים של 4 אותיות עם <b>צירופי עיצורים</b> (כמו ST, SW, CL, TR). מקריאים את צמד העיצורים ברצף מהיר.</div>\n                    <div class="rule-examples">\n                        <b>דוגמאות להסבר בלבד (לא מופיעות בתרגול):</b><br>\n                        • <b>PIG</b> (פִּג) - חזיר<br>\n                        • <b>MILK</b> (מִלְכּ) - חלב<br>\n                        • <b>SWIM</b> (סְוִים) - לשחות\n                    </div>\n                ',
    cards: [
      {
        en: "BIG",
        he: "בִּג",
        meaning: "גדול",
      },
      {
        en: "CLIP",
        he: "כְּלִפ",
        meaning: "מהדק / קליפ",
      },
      {
        en: "PINK",
        he: "פִּנְכּ",
        meaning: "ורוד",
      },
      {
        en: "GIFT",
        he: "גִּפְט",
        meaning: "מתנה",
      },
      {
        en: "SLIM",
        he: "סְלִים",
        meaning: "רזה",
      },
      {
        en: "WIN",
        he: "וִין",
        meaning: "לנצח",
      },
      {
        en: "HIT",
        he: "הִט",
        meaning: "להכות",
      },
      {
        en: "SIT",
        he: "סִט",
        meaning: "לשבת",
      },
      {
        en: "LIP",
        he: "לִפ",
        meaning: "שפה",
      },
      {
        en: "DIG",
        he: "דִּג",
        meaning: "לחפור",
      },
      {
        en: "FIT",
        he: "פִּט",
        meaning: "מתאים / בכושר",
      },
      {
        en: "PIN",
        he: "פִּן",
        meaning: "סיכה",
      },
      {
        en: "TRIP",
        he: "טְרִפ",
        meaning: "טיול",
      },
      {
        en: "GRIN",
        he: "גְרִין",
        meaning: "חיוך רחב",
      },
      {
        en: "SPIN",
        he: "סְפִּין",
        meaning: "לסובב",
      },
      {
        en: "SPIT",
        he: "סְפִּט",
        meaning: "לירוק",
      },
      {
        en: "LIFT",
        he: "לִפְט",
        meaning: "להרים / מעלית",
      },
      {
        en: "MINT",
        he: "מִנְט",
        meaning: "נענע / מנטה",
      },
    ],
  },
  {
    id: "rev1_3",
    tabName: "מסכם 1+2+3",
    title: "תרגול מסכם: מודולים 1 + 2 + 3 (A, O, I)",
    rule: '\n                    <div class="rule-section"><b>מטרת התרגול:</b> תרגול משולב של שלוש התנועות הראשונות במבנים של 3 ו-4 אותיות.</div>\n                    <div class="rule-section"><b>שיטת עבודה מומלצת:</b> 1. מזהים את האות התנועתית במרכז (A/O/I). 2. שולפים את הניקוד המתאים (פתח/חולם/חיריק). 3. מחברים את העיצורים.</div>\n                ',
    cards: [
      {
        en: "HAT",
        he: "הַט",
        meaning: "כובע (פתח)",
      },
      {
        en: "FOX",
        he: "פֹכּס",
        meaning: "שועל (חולם)",
      },
      {
        en: "BIG",
        he: "בִּג",
        meaning: "גדול (חיריק)",
      },
      {
        en: "MAN",
        he: "מַן",
        meaning: "איש (פתח)",
      },
      {
        en: "POT",
        he: "פֹט",
        meaning: "סיר (חולם)",
      },
      {
        en: "CLIP",
        he: "כְּלִפ",
        meaning: "מהדק (חיריק)",
      },
      {
        en: "BAT",
        he: "בַּט",
        meaning: "מחבט (פתח)",
      },
      {
        en: "JOB",
        he: "גֹ'ב",
        meaning: "עבודה (חולם)",
      },
      {
        en: "PINK",
        he: "פִּנְכּ",
        meaning: "ורוד (חיריק)",
      },
      {
        en: "FAN",
        he: "פַן",
        meaning: "מאוורר (פתח)",
      },
      {
        en: "LOG",
        he: "לֹג",
        meaning: "בול עץ (חולם)",
      },
      {
        en: "GIFT",
        he: "גִּפְט",
        meaning: "מתנה (חיריק)",
      },
      {
        en: "DAD",
        he: "דַד",
        meaning: "אבא (פתח)",
      },
      {
        en: "FOG",
        he: "פֹג",
        meaning: "ערפל (חולם)",
      },
      {
        en: "TRIP",
        he: "טְרִפ",
        meaning: "טיול (חיריק)",
      },
      {
        en: "MAD",
        he: "מַד",
        meaning: "כועס (פתח)",
      },
      {
        en: "HOP",
        he: "הֹפ",
        meaning: "לקפוץ (חולם)",
      },
      {
        en: "MINT",
        he: "מִנְט",
        meaning: "נענע (חיריק)",
      },
    ],
  },
]

/** Prefilled into the JSON loader's textarea as a starting point. */
export const sampleModule: PracticeModule = {
  id: "mod_sample_e",
  tabName: "מודול (E)",
  title: "מודול דוגמה: תנועת E קצרה (Short E)",
  rule: '<div class="rule-section"><b>הסבר וחוקיות:</b> כשהאות <b>E</b> מופיעה באמצע מילה קצרה, היא מקבלת צליל "אֶה" קצר (סגול).</div>\n<div class="rule-section"><b>סימון הניקוד:</b> נסמן את הצליל הזה תמיד עם <b>סגול ( ֶ )</b>.</div>',
  cards: [
    {
      en: "RED",
      he: "רֶד",
      meaning: "אדום",
    },
    {
      en: "BED",
      he: "בֶּד",
      meaning: "מיטה",
    },
    {
      en: "PEN",
      he: "פֶּן",
      meaning: "עט",
    },
    {
      en: "TEN",
      he: "תֶּן",
      meaning: "עשר",
    },
    {
      en: "NET",
      he: "נֶת",
      meaning: "רשת",
    },
    {
      en: "PET",
      he: "פֶּט",
      meaning: "חיית מחמד",
    },
    {
      en: "LEG",
      he: "לֶג",
      meaning: "רגל",
    },
    {
      en: "HEN",
      he: "הֶן",
      meaning: "תרנגולת",
    },
  ],
}

/** Ids of the built-in modules, used to tell them apart from user-added ones. */
export const builtInModuleIds: readonly string[] = [
  "mod1",
  "mod2",
  "rev1_2",
  "mod3",
  "rev1_3",
]
